name = "AtomicChannels"
uuid = "44ab9252-467d-406b-8247-97505f0e2540"
authors = ["Dr. Jiacheng Chuan <jiacheng_chuan@outlook.com> and contributors"]
version = "1.0.1"

[compat]
julia = "^1.8"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown", "Test"]
